
Games = [	'Metroid',
								'The Legend of Zelda',
								'Contra',
								'Castlevania',
								'Rygar',
								'Super Mario Bros',
								'Popeye',
								'Super Mario Bros 2',
								'Super Mario Bros 3',
								'Castlevania 2',
								'Batman: Return of the Joker',
								'Double Dribble',
								'Double Strike',
								'Dr. Mario',
								'Dragon Warrior III',
								'Dragon Wars',
								'Dragons of Flame',
								'Duck Hunt',
								'Déjà Vu: A Nightmare Comes True',
								'Elite',
								'Excitebike',
								'Exodus: Ultima III',
								'F-15 Strike Eagle',
								'Family Feud',
								'The Fantastic Adventures of Dizzy',
								'Faxanadu',
								'Final Fantasy',
								'Final Fantasy II',
								'Final Fantasy III',
								'Flight of the Intruder',
								'Friday the 13th',
								'Galaxian',
								'Gauntlet',
								'Gauntlet II',
								'Gemfire',
								'Genghis Khan',
								'Ghostbusters',
								'Ghosts N Goblins',
								'Golf',
								'The Goonies II',
								'Gradius',
								'The Guardian Legend',
								'Guerrilla War',
								'Gumshoe',
								'Gyromite',
								'Gyruss',
								'Heroes of the Lance',
								'High Speed',
								'Hillsfar',
								'Hogans Alley',
								'Hook',
								'Hoops',
								'Ice Hockey',
								'Ikari Warriors',
								'Ikari Warriors II: Victory Road',
								'The Immortal',
								'Impossible Mission II',
								'Indiana Jones and the Last Crusade: The Action ...',
								'Indiana Jones and the Temple of Doom',
								'Jack Nicklaus Greatest 18 Holes of Major Champ...',
								'Joe & Mac: Caveman Ninja',
								'John Elways Quarterback',
								'Jordan vs. Bird: One-on-One',
								'Journey to Silius',
								'Joust',
								'Karate Champ',
								'Karateka',
								'Karnov',
								'Kid Dracula',
								'Kings of the Beach',
								'Klax',
								'Krustys Fun House',
								'Kung-Fu Master',
								'Last Ninja 2: Back with a Vengeance',
								'The Legend of Zelda',
								'Lemmings',
								'Lethal Weapon',
								'Life Force',
								'Little Nemo: The Dream Master',
								'Lode Runner',
								'Low G Man',
								'The Magic Candle',
								'Maniac Mansion',
								'Marble Madness',
								'Mario Bros.',
								'Mario is Missing!',
								'Mega Man',
								'Mega Man 2',
								'Mega Man 3',
								'Mega Man 4',
								'Mega Man 5',
								'Mega Man 6',
								'Metal Gear',
								'Metroid',
								'Micro Machines',
								'Might and Magic: Book I',
								'Monopoly',
								'Ms. Pac-Man',
								'The Mutant Virus',
								'Ninja Gaiden',
								'Ninja Gaiden II: The Dark Sword of Chaos',
								'Ninja Gaiden III: The Ancient Ship of Doom',
								'Nobunagas Ambition',
								'Nobunagas Ambition II',
								'North & South',
								'Operation Europe: Path to Victory 1939-45',
								'Operation Wolf',
								'Othello',
								'Overlord',
								'P.O.W.: Prisoners of War',
								'Pac-Man',
								'Paperboy',
								'Parasol Stars: The Story of Bubble Bobble III',
								'Pipe Dream',
								'Platoon',
								'Pool of Radiance',
								'Prince of Persia',
								'QIX',
								'Quattro Adventure',
								'Quattro Sports',
								'R.C. Pro-Am',
								'Rad Racer',
								'Rainbow Islands',
								'Rampage',
								'Rampart',
								'River City Ransom',
								'RoboCop',
								'Rock n Ball',
								'Rocket Ranger',
								'Rollerball',
								'Rolling Thunder',
								'Rushn Attack',
								'Shadowgate',
								'Shinobi',
								'Shockwave',
								'Sid Meiers Pirates!',
								'Silent Service',
								'The Simpsons: Bart vs. the Space Mutants',
								'The Simpsons: Bart vs. the World',
								'The Simpsons: Bartman Meets Radioactive Man',
								'Skate or Die',
								'Ski or Die',
								'Sky Shark',
								'Snakes Revenge',
								'Solar Jetman: Hunt for the Golden Warpship',
								'Solstice: The Quest for the Staff of Demnos',
								'Speedball',
								'Spy Hunter',
								'Spy vs. Spy',
								'Star Soldier',
								'Star Wars',
								'Star Wars: The Empire Strikes Back',
								'Stargate',
								'StarTropics',
								'Super C',
								'Super Mario Bros.',
								'Super Mario Bros. 2',
								'Super Mario Bros. 3',
								'Super Sprint',
								'Tag Team Wrestling',
								'Tales of the Unknown, Volume I: The Bards Tale',
								'Target: Renegade',
								'Tecmo Bowl',
								'Teenage Mutant Ninja Turtles',
								'Teenage Mutant Ninja Turtles II: The Arcade Game',
								'Tennis',
								'Tetris',
								'Tetris 2',
								'Thexder',
								'The Three Stooges',
								'Tiles of Fate',
								'Times of Lore',
								'Tiny Toon Adventures',
								'Toobin',
								'Tower Toppler',
								'Treasure Island Dizzy',
								'Ultima IV: Quest of the Avatar',
								'Ultima V: Warriors of Destiny',
								'Uncharted Waters',
								'Uninvited',
								'Valis: The Fantasm Soldier',
								'Volleyball',
								'Walt Disneys The Jungle Book',
								'Where in Time is Carmen Sandiego?',
								'Win, Lose, or Draw',
								'Winter Games',
								'Wizardry II: The Knight of Diamonds',
								'Wizardry III: Legacy of Llylgamyn',
								'Wizardry: Proving Grounds of the Mad Overlord',
								'World Games',
								'Wrath of the Black Manta',
								'Wrecking Crew',
								'Xenophobe',
								'Yoshi',
								'Yoshis Cookie',
								'Ys',
								'Zelda II: The Adventure of Link'								
								]
								
