
# Sega Master System (SMS)

SMS_Games = [	"Ace of Aces",
								"Action Fighter",
								"The Addams Family",
								"Aerial Assault",
								"After Burner",
								"Alex Kidd in Miracle World",
								"Alex Kidd in Shinobi World",
								"Alex Kidd: BMX Trial",
								"Alex Kidd: High-Tech World",
								"Alex Kidd: The Lost Stars",
								"ALF",
								"Alien Storm",
								"Alien Syndrome",
								"Alien³",
								"Altered Beast",
								"The Amazing Spider-Man vs. The Kingpin",
								"Assault City",
								"Astro Warrior",
								"Astro Warrior / Pit Pot",
								"Asterix",
								"Asterix and the Great Rescue",
								"Ayrton Senna's Super Monaco GP II",
								"Aztec Adventure: The Golden Road to Paradise",
								"Back to the Future Part II",
								"Back to the Future Part III",
								"Baku Baku Animal",
								"Bank Panic",
								"Batman Returns",
								"Battle Out Run",
								"Battletoads in Battlemaniacs",
								"Black Belt",
								"Blade Eagle 3-D",
								"Bomber Raid",
								"Bonanza Bros.",
								"Bram Stoker's Dracula",
								"Bubble Bobble",
								"California Games",
								"California Games II",
								"Captain Silver",
								"Chase H.Q.",
								"Chase H.Q. II: Special Criminal Investigation",
								"Cheese Cat-Astrophe starring Speedy Gonzales",
								"Choplifter!",
								"Chuck Rock",
								"Chuck Rock II: Son of Chuck",
								"Cloud Master",
								"Columns",
								"Cool Spot",
								"Cosmic Spacehead",
								"Cyber Shinobi: Shinobi Part 2",
								"Cyborg Hunter",
								"Danan the Jungle Fighter",
								"Dead Angle",
								"Deep Duck Trouble starring Donald Duck",
								"Desert Speedtrap starring Road Runner and Wile ...",
								"Desert Strike: Return to the Gulf",
								"Dick Tracy",
								"Disney's Aladdin",
								"Disney's Ariel the Little Mermaid",
								"Double Dragon",
								"Double Hawk",
								"Dr. Robotnik's Mean Bean Machine",
								"Dragon Crystal",
								"Dragon: The Bruce Lee Story",
								"Dynamite Duke",
								"Dynamite Düx",
								"Dynamite Headdy",
								"E-SWAT: Cyber Police",
								"Earthworm Jim",
								"Ecco the Dolphin",
								"Ecco: The Tides of Time",
								"Enduro Racer",
								"F1",
								"F16 Fighting Falcon",
								"The Fantastic Adventures of Dizzy",
								"Fantasy Zone",
								"Fantasy Zone II: The Tears of Opa-Opa",
								"Fantasy Zone: The Maze",
								"FIFA International Soccer",
								"Fire & Forget II",
								"Fire & Ice",
								"The Flintstones",
								"Forgotten Worlds",
								"G-Loc Air Battle",
								"Gain Ground",
								"Galactic Protector",
								"Galaxy Force",
								"Gangster Town",
								"Gauntlet",
								"Ghost House",
								"Ghostbusters",
								"Ghouls 'N Ghosts",
								"Global Defense",
								"Global Gladiators",
								"Golden Axe",
								"Golden Axe Warrior",
								"Golvellius: Valley of Doom",
								"Great Baseball",
								"Great Basketball",
								"Great Golf",
								"Hang On & Safari Hunt",
								"Hang-On",
								"Heroes of the Lance",
								"Hokuto no Ken",
								"Impossible Mission",
								"The Incredible Crash Dummies",
								"Indiana Jones and the Last Crusade: The Action ...",
								"Ivan 'Iron Man' Stewart's Super Off Road",
								"James Bond 007: The Duel",
								"James Pond 2: Codename: RoboCod",
								"Kenseiden",
								"King's Quest",
								"Klax",
								"Krusty's Fun House",
								"Kung Fu Kid",
								"Land of Illusion starring Mickey Mouse",
								"Laser Ghost",
								"Legend of Illusion starring Mickey Mouse",
								"Lemmings",
								"The Lion King",
								"Lord of the Sword",
								"The Lucky Dime Caper starring Donald Duck",
								"Marble Madness",
								"Master of Darkness",
								"Maze Hunter 3-D",
								"Mercs",
								"Michael Jackson's Moonwalker",
								"Micro Machines",
								"Miracle Warriors: Seal of the Dark Lord",
								"Missile Defense 3-D",
								"Monopoly",
								"Montezuma's Revenge",
								"Mortal Kombat",
								"Mortal Kombat 3",
								"Mortal Kombat II",
								"Ms. Pac-Man",
								"My Hero",
								"Mnica no Castelo do Drago",
								"The New Zealand Story",
								"Ninja Gaiden",
								"The Ninja",
								"Olympic Gold: Barcelona '92",
								"Operation Wolf",
								"OutRun",
								"OutRun Europa",
								"Pac-Mania",
								"Paperboy",
								"Parlour Games",
								"Penguin Land",
								"PGA Tour Golf",
								"Phantasy Star",
								"Pit Pot: The Magical Castle",
								"Pit-Fighter",
								"Populous",
								"Poseidon Wars 3-D",
								"Power Strike",
								"Power Strike II",
								"Predator 2",
								"Prince of Persia",
								"Psychic World",
								"Psycho Fox",
								"Putt & Putter",
								"Quartet",
								"R-Type",
								"R.C. Grand Prix",
								"Rainbow Islands",
								"Rambo: First Blood Part II",
								"Rampage",
								"Rampart",
								"Rastan",
								"Renegade",
								"Rescue Mission",
								"Rise of the Robots",
								"Road Rash",
								"RoboCop 3",
								"RoboCop Versus the Terminator",
								"Rygar",
								"Safari Hunt",
								"Sagaia",
								"Scramble Spirits",
								"SDI: Strategic Defense Initiative",
								"Secret Commando",
								"Sensible Soccer: European Champions: 92/93 Edition",
								"Shadow Dancer",
								"Shadow of the Beast",
								"Shanghai",
								"Shinobi",
								"Shooting Gallery",
								"The Simpsons: Bart vs. the Space Mutants",
								"The Simpsons: Bart vs. the World",
								"Smash T.V.",
								"The Smurfs",
								"Solomon's Key",
								"Sonic Blast",
								"Sonic the Hedgehog 2",
								"Sonic the Hedgehog Chaos",
								"Sonic the Hedgehog: Spinball",
								"Space Gun",
								"Space Harrier",
								"Space Harrier 3-D",
								"Speedball",
								"Speedball 2: Brutal Deluxe",
								"SpellCaster",
								"Spider-Man: Return of the Sinister Six",
								"Spy vs. Spy",
								"Star Wars",
								"Street Fighter II': Special Champion Edition",
								"Streets of Rage",
								"Streets of Rage 2",
								"Strider",
								"Strider 2",
								"Summer Games",
								"Super Kick Off",
								"Super Monaco GP",
								"T2: The Arcade Game",
								"Taito's Super Space Invaders",
								"Taz in Escape from Mars",
								"Taz-Mania",
								"Teddy Boy",
								"Tennis Ace",
								"Terminator 2: Judgment Day",
								"The Terminator",
								"ThunderBlade",
								"Time Soldiers",
								"TransBot",
								"Turma da Mônica em: O Resgate",
								"Ultima IV: Quest of the Avatar",
								"Ultimate Soccer",
								"Vigilante",
								"Wanted",
								"Where in the World is Carmen Sandiego?",
								"Wimbledon Championship Tennis",
								"Winter Olympics: Lillehammer '94",
								"Wolfchild",
								"Wonder Boy",
								"Wonder Boy III: The Dragon's Trap",
								"Wonder Boy in Monster Land",
								"Wonder Boy in Monster World",
								"World Championship Soccer",
								"World Class Leader Board",
								"World Cup USA '94",
								"World Games",
								"World Grand Prix",
								"Xenon 2: Megablast",
								"Xevious",
								"Ys",
								"Zaxxon 3-D",
								"Zillion",
								"Zillion 2: Tri Formation",
								"Zool"	
]

